[pytest]
testpaths = tests/pytest
pythonpath = .
addopts = --cov=creditcard_fraud.preprocess --cov=creditcard_fraud.api.main --cov=creditcard_fraud.ge_validation --cov-report=term-missing --cov-fail-under=80
